// Array de perguntas por tema (100 perguntas por tema)
const themes = {
    friends: [
      "Quem é a pessoa mais engraçada do grupo?",
      "Qual foi a maior confusão que você já se meteu com amigos?",
      "Se você pudesse trocar de vida com alguém aqui, quem seria?",
      "Qual é o segredo mais vergonhoso que você guarda?",
      "Quem do grupo seria o melhor amigo de infância?",
        "Quem é a pessoa mais engraçada do grupo?",
        "Qual foi a maior confusão que você já se meteu com amigos?",
        "Se você pudesse trocar de vida com alguém aqui, quem seria?",
        "Qual é o segredo mais vergonhoso que você guarda?",
        "Quem do grupo seria o melhor amigo de infância?",
        "Quem do grupo é mais provável de se tornar famoso?",
        "Qual foi a maior mentira que você já contou para um amigo?",
        "Quem do grupo seria o melhor em uma competição de comédia?",
        "Qual foi a coisa mais estranha que você já fez por um amigo?",
        "Se você pudesse escolher qualquer pessoa do grupo para ser seu colega de quarto, quem seria?",
        "Quem do grupo é mais provável de esquecer seu aniversário?",
        "Qual foi a maior confusão que você já causou sem querer?",
        "Quem do grupo tem o pior senso de direção?",
        "Qual foi a coisa mais engraçada que aconteceu durante uma viagem com amigos?",
        "Quem do grupo seria o melhor em uma competição de videogame?",
        "Qual foi a última vez que você riu tanto que chorou?",
        "Quem do grupo é mais provável de se perder em um shopping?",
        "Qual foi a coisa mais boba que você já brigou com um amigo?",
        "Quem do grupo é mais provável de ser pego falando sozinho?",
        "Qual foi a maior surpresa que você já recebeu de um amigo?",
        "Quem do grupo seria o melhor em uma competição de karaoke?",
        "Qual foi a coisa mais estranha que você já pediu emprestado?",
        "Quem do grupo é mais provável de esquecer onde estacionou o carro?",
        "Qual foi a coisa mais engraçada que você já ouviu de um amigo bêbado?",
        "Quem do grupo é mais provável de se tornar um influenciador digital?",
        "Qual foi a coisa mais louca que você já fez com seus amigos?",
        "Quem do grupo é mais provável de esquecer o próprio nome em uma situação estressante?",
        "Qual foi a maior aventura que você já teve com seus amigos?",
        "Quem do grupo seria o melhor em uma competição de dança?",
        "Qual foi a coisa mais estranha que você já comeu por causa de uma aposta?",
        "Quem do grupo é mais provável de se perder em uma festa?",
        "Qual foi a coisa mais engraçada que você já fez para impressionar alguém?",
        "Quem do grupo é mais provável de esquecer o celular em casa?",
        "Qual foi a coisa mais boba que você já comprou para um amigo?",
        "Quem do grupo seria o melhor em uma competição de memes?",
        "Qual foi a coisa mais inesperada que um amigo já fez por você?",
        "Quem do grupo é mais provável de se atrasar para tudo?",
        "Qual foi a coisa mais estranha que você já usou como roupa?",
        "Quem do grupo é mais provável de esquecer o próprio aniversário?",
        "Qual foi a coisa mais engraçada que você já ouviu de um amigo dormindo?",
        "Quem do grupo seria o melhor em uma competição de piadas?",
        "Qual foi a coisa mais louca que você já fez por um desafio?",
        "Quem do grupo é mais provável de esquecer onde está sua casa?",
        "Qual foi a coisa mais estranha que você já fez por dinheiro?",
        "Quem do grupo seria o melhor em uma competição de selfies?",
        "Qual foi a coisa mais engraçada que você já fez sem querer?",
        "Quem do grupo é mais provável de esquecer o próprio número de telefone?",
        "Qual foi a coisa mais boba que você já fez por um amigo?",
        "Quem do grupo é mais provável de se perder em um parque?",
        "Qual foi a coisa mais estranha que você já fez por diversão?",
        "Quem do grupo seria o melhor em uma competição de imitações?",
        "Qual foi a coisa mais engraçada que você já fez na escola?",
        "Quem do grupo é mais provável de esquecer o próprio endereço?",
        "Qual foi a coisa mais louca que você já fez em uma festa?",
        "Quem do grupo seria o melhor em uma competição de histórias engraçadas?",
        "Qual foi a coisa mais estranha que você já fez por amor?",
        "Quem do grupo é mais provável de esquecer o próprio horário de trabalho?",
        "Qual foi a coisa mais engraçada que você já fez com um animal de estimação?",
        "Quem do grupo seria o melhor em uma competição de risadas?",
        "Qual foi a coisa mais boba que você já fez por uma aposta?",
        "Quem do grupo é mais provável de esquecer o próprio nome em público?",
        "Qual foi a coisa mais estranha que você já fez por curiosidade?",
        "Quem do grupo seria o melhor em uma competição de mímica?",
        "Qual foi a coisa mais engraçada que você já fez no trabalho?",
        "Quem do grupo é mais provável de esquecer o próprio carro ligado?",
        "Qual foi a coisa mais louca que você já fez por um desafio?",
        "Quem do grupo seria o melhor em uma competição de caretas?",
        "Qual foi a coisa mais estranha que você já fez por um amigo?",
        "Quem do grupo é mais provável de esquecer o próprio casaco em um bar?",
        "Qual foi a coisa mais engraçada que você já fez em uma viagem?",
        "Quem do grupo seria o melhor em uma competição de piadas ruins?",
        "Qual foi a coisa mais boba que você já fez por diversão?",
        "Quem do grupo é mais provável de esquecer o próprio sobrenome?",
        "Qual foi a coisa mais estranha que você já fez por uma brincadeira?",
        "Quem do grupo seria o melhor em uma competição de histórias assustadoras?",
        "Qual foi a coisa mais engraçada que você já fez em uma festa de aniversário?",
        "Quem do grupo é mais provável de esquecer o próprio celular no banheiro?",
        "Qual foi a coisa mais louca que você já fez por um amigo?",
        "Quem do grupo seria o melhor em uma competição de dança improvisada?",
        "Qual foi a coisa mais estranha que você já fez por uma aposta?",
        "Quem do grupo é mais provável de esquecer o próprio nome em uma entrevista?",
        "Qual foi a coisa mais engraçada que você já fez em uma reunião?",
        "Quem do grupo seria o melhor em uma competição de imitações de celebridades?",
        "Qual foi a coisa mais boba que você já fez por um desafio?",
        "Quem do grupo é mais provável de esquecer o próprio endereço em uma viagem?",
        "Qual foi a coisa mais estranha que você já fez por diversão?",
        "Quem do grupo seria o melhor em uma competição de histórias românticas?",
        "Qual foi a coisa mais engraçada que você já fez em uma festa de casamento?",
        "Quem do grupo é mais provável de esquecer o próprio carro em um estacionamento?",
        "Qual foi a coisa mais louca que você já fez por uma aposta?",
        "Quem do grupo seria o melhor em uma competição de risadas forçadas?",
        "Qual foi a coisa mais estranha que você já fez por um amigo?",
        "Quem do grupo é mais provável de esquecer o próprio nome em um encontro?",
        "Qual foi a coisa mais engraçada que você já fez em uma festa de Halloween?",
        "Quem do grupo seria o melhor em uma competição de histórias de terror?",
        "Qual foi a coisa mais boba que você já fez por diversão?",
        "Quem do grupo é mais provável de esquecer o próprio sobrenome em um formulário?",
        "Qual foi a coisa mais estranha que você já fez por uma brincadeira?",
        "Quem do grupo seria o melhor em uma competição de imitações de animais?",
        "Qual foi a coisa mais engraçada que você já fez em uma festa de Réveillon?"
    ],
    plus18: [
      "Qual foi o momento mais quente da sua vida?",
      "Você já fez algo ousado em público? Conte!",
      "Quem do grupo tem o maior charme?",
      "O que você faria se ficasse sozinho(a) com seu crush?",
      "Qual é o segredo mais picante que você guarda?",
        "Qual foi o momento mais íntimo da sua vida?",
        "Você já fez algo ousado em público? Conte!",
        "Quem do grupo tem o maior charme?",
        "O que você faria se ficasse sozinho(a) com seu crush?",
        "Qual é o segredo mais picante que você guarda?",
        "Qual foi a coisa mais ousada que você já fez em um relacionamento?",
        "Quem do grupo seria o mais provável de fazer uma declaração pública de amor?",
        "Qual foi a coisa mais inusitada que você já fez por paixão?",
        "Quem do grupo é mais provável de mandar uma mensagem errada para o crush?",
        "Qual foi a coisa mais estranha que você já fez por desejo?",
        "Quem do grupo seria o mais provável de fazer uma surpresa romântica?",
        "Qual foi a coisa mais engraçada que aconteceu em um encontro?",
        "Quem do grupo é mais provável de se apaixonar à primeira vista?",
        "Qual foi a coisa mais louca que você já fez por amor?",
        "Quem do grupo seria o mais provável de fazer uma proposta de casamento criativa?",
        "Qual foi a coisa mais inesperada que você já fez por um relacionamento?",
        "Quem do grupo é mais provável de esquecer o nome do crush?",
        "Qual foi a coisa mais estranha que você já fez por ciúmes?",
        "Quem do grupo seria o mais provável de fazer uma surpresa sensual?",
        "Qual foi a coisa mais engraçada que você já ouviu de um ex?",
        "Quem do grupo é mais provável de se declarar bêbado?",
        "Qual foi a coisa mais louca que você já fez por desejo?",
        "Quem do grupo seria o mais provável de fazer uma viagem romântica espontânea?",
        "Qual foi a coisa mais inusitada que você já fez por paixão?",
        "Quem do grupo é mais provável de esquecer o aniversário do parceiro?",
        "Qual foi a coisa mais estranha que você já fez por amor?",
        "Quem do grupo seria o mais provável de fazer uma declaração romântica em público?",
        "Qual foi a coisa mais engraçada que você já fez em um encontro às cegas?",
        "Quem do grupo é mais provável de mandar mensagens picantes por engano?",
        "Qual foi a coisa mais louca que você já fez por desejo?",
        "Quem do grupo seria o mais provável de fazer uma surpresa inesquecível?",
        "Qual foi a coisa mais inusitada que você já fez por paixão?",
        "Quem do grupo é mais provável de esquecer o nome do parceiro?",
        "Qual foi a coisa mais estranha que você já fez por ciúmes?",
        "Quem do grupo seria o mais provável de fazer uma declaração romântica criativa?",
        "Qual foi a coisa mais engraçada que você já ouviu de um crush?",
        "Quem do grupo é mais provável de se apaixonar por um amigo?",
        "Qual foi a coisa mais louca que você já fez por amor?",
        "Quem do grupo seria o mais provável de fazer uma surpresa sensual?",
        "Qual foi a coisa mais inusitada que você já fez por paixão?",
        "Quem do grupo é mais provável de esquecer o aniversário do crush?",
        "Qual foi a coisa mais estranha que você já fez por desejo?",
        "Quem do grupo seria o mais provável de fazer uma declaração romântica em público?",
        "Qual foi a coisa mais engraçada que você já fez em um encontro às cegas?",
        "Quem do grupo é mais provável de mandar mensagens picantes por engano?",
        "Qual foi a coisa mais louca que você já fez por desejo?",
        "Quem do grupo seria o mais provável de fazer uma surpresa inesquecível?",
        "Qual foi a coisa mais inusitada que você já fez por paixão?",
        "Quem do grupo é mais provável de esquecer o nome do parceiro?",
        "Qual foi a coisa mais estranha que você já fez por ciúmes?",
        "Quem do grupo seria o mais provável de fazer uma declaração romântica criativa?",
        "Qual foi a coisa mais engraçada que você já ouviu de um crush?",
        "Quem do grupo é mais provável de se apaixonar por um amigo?",
        "Qual foi a coisa mais louca que você já fez por amor?",
        "Quem do grupo seria o mais provável de fazer uma surpresa sensual?",
        "Qual foi a coisa mais inusitada que você já fez por paixão?",
        "Quem do grupo é mais provável de esquecer o aniversário do crush?",
        "Qual foi a coisa mais estranha que você já fez por desejo?",
        "Quem do grupo seria o mais provável de fazer uma declaração romântica em público?",
        "Qual foi a coisa mais engraçada que você já fez em um encontro às cegas?",
        "Quem do grupo é mais provável de mandar mensagens picantes por engano?",
        "Qual foi a coisa mais louca que você já fez por desejo?",
        "Quem do grupo seria o mais provável de fazer uma surpresa inesquecível?",
        "Qual foi a coisa mais inusitada que você já fez por paixão?",
        "Quem do grupo é mais provável de esquecer o nome do parceiro?",
        "Qual foi a coisa mais estranha que você já fez por ciúmes?",
        "Quem do grupo seria o mais provável de fazer uma declaração romântica criativa?",
        "Qual foi a coisa mais engraçada que você já ouviu de um crush?",
        "Quem do grupo é mais provável de se apaixonar por um amigo?",
        "Qual foi a coisa mais louca que você já fez por amor?",
        "Quem do grupo seria o mais provável de fazer uma surpresa sensual?",
        "Qual foi a coisa mais inusitada que você já fez por paixão?",
        "Quem do grupo é mais provável de esquecer o aniversário do crush?",
        "Qual foi a coisa mais estranha que você já fez por desejo?",
        "Quem do grupo seria o mais provável de fazer uma declaração romântica em público?",
        "Qual foi a coisa mais engraçada que você já fez em um encontro às cegas?",
        "Quem do grupo é mais provável de mandar mensagens picantes por engano?",
        "Qual foi a coisa mais louca que você já fez por desejo?",
        "Quem do grupo seria o mais provável de fazer uma surpresa inesquecível?",
        "Qual foi a coisa mais inusitada que você já fez por paixão?",
        "Quem do grupo é mais provável de esquecer o nome do parceiro?",
        "Qual foi a coisa mais estranha que você já fez por ciúmes?",
        "Quem do grupo seria o mais provável de fazer uma declaração romântica criativa?",
        "Qual foi a coisa mais engraçada que você já ouviu de um crush?",
        "Quem do grupo é mais provável de se apaixonar por um amigo?",
        "Qual foi a coisa mais louca que você já fez por amor?",
        "Quem do grupo seria o mais provável de fazer uma surpresa sensual?",
        "Qual foi a coisa mais inusitada que você já fez por paixão?",
        "Quem do grupo é mais provável de esquecer o aniversário do crush?",
        "Qual foi a coisa mais estranha que você já fez por desejo?",
        "Quem do grupo seria o mais provável de fazer uma declaração romântica em público?",
        "Qual foi a coisa mais engraçada que você já fez em um encontro às cegas?",
        "Quem do grupo é mais provável de mandar mensagens picantes por engano?",
        "Qual foi a coisa mais louca que você já fez por desejo?",
        "Quem do grupo seria o mais provável de fazer uma surpresa inesquecível?"  
    ],
    drinks: [
      "Quem bebeu mais na última festa?",
      "Qual é a bebida mais estranha que você já experimentou?",
      "Se você fosse um drink, qual seria?",
      "Quem do grupo aguenta mais shots?",
      "Qual foi a maior gafe que você já fez bêbado(a)?",
        "Quem do grupo já bebeu mais de 10 shots em uma noite?",
        "Qual foi a bebida mais estranha que você já experimentou?",
        "Se você fosse um drink, qual seria?",
        "Quem do grupo aguenta mais shots?",
        "Qual foi a maior gafe que você já fez bêbado(a)?",
        "Quem do grupo já vomitou em uma festa?",
        "Qual foi a coisa mais engraçada que você já fez bêbado(a)?",
        "Quem do grupo já bebeu até perder a memória?",
        "Qual foi a coisa mais estranha que você já fez por uma aposta envolvendo bebidas?",
        "Quem do grupo já tomou uma multa por dirigir bêbado?",
        "Qual foi a coisa mais louca que você já fez em uma festa?",
        "Quem do grupo já bebeu algo que não deveria?",
        "Qual foi a coisa mais engraçada que você já ouviu de um amigo bêbado?",
        "Quem do grupo já tentou fazer um drink e falhou miseravelmente?",
        "Qual foi a coisa mais estranha que você já pediu em um bar?",
        "Quem do grupo já bebeu algo que parecia água, mas não era?",
        "Qual foi a coisa mais louca que você já fez por uma aposta envolvendo bebidas?",
        "Quem do grupo já bebeu algo que tinha gosto de remédio?",
        "Qual foi a coisa mais engraçada que você já fez bêbado(a)?",
        "Quem do grupo já bebeu algo que parecia suco, mas não era?",
        "Qual foi a coisa mais estranha que você já pediu em um bar?",
        "Quem do grupo já bebeu algo que parecia refrigerante, mas não era?",
        "Qual foi a coisa mais louca que você já fez por uma aposta envolvendo bebidas?",
        "Quem do grupo já bebeu algo que tinha gosto de xarope?",
        "Qual foi a coisa mais engraçada que você já fez bêbado(a)?",
        "Quem do grupo já bebeu algo que parecia chá, mas não era?",
        "Qual foi a coisa mais estranha que você já pediu em um bar?",
        "Quem do grupo já bebeu algo que parecia leite, mas não era?",
        "Qual foi a coisa mais louca que você já fez por uma aposta envolvendo bebidas?",
        "Quem do grupo já bebeu algo que tinha gosto de limonada, mas não era?",
        "Qual foi a coisa mais engraçada que você já fez bêbado(a)?",
        "Quem do grupo já bebeu algo que parecia café, mas não era?",
        "Qual foi a coisa mais estranha que você já pediu em um bar?",
        "Quem do grupo já bebeu algo que parecia chocolate, mas não era?",
        "Qual foi a coisa mais louca que você já fez por uma aposta envolvendo bebidas?",
        "Quem do grupo já bebeu algo que tinha gosto de suco de laranja, mas não era?",
        "Qual foi a coisa mais engraçada que você já fez bêbado(a)?",
        "Quem do grupo já bebeu algo que parecia refrigerante de cola, mas não era?",
        "Qual foi a coisa mais estranha que você já pediu em um bar?",
        "Quem do grupo já bebeu algo que parecia água tônica, mas não era?",
        "Qual foi a coisa mais louca que você já fez por uma aposta envolvendo bebidas?",
        "Quem do grupo já bebeu algo que tinha gosto de chá gelado, mas não era?",
        "Qual foi a coisa mais engraçada que você já fez bêbado(a)?",
        "Quem do grupo já bebeu algo que parecia suco de abacaxi, mas não era?",
        "Qual foi a coisa mais estranha que você já pediu em um bar?",
        "Quem do grupo já bebeu algo que parecia suco de maracujá, mas não era?",
        "Qual foi a coisa mais louca que você já fez por uma aposta envolvendo bebidas?",
        "Quem do grupo já bebeu algo que tinha gosto de suco de uva, mas não era?",
        "Qual foi a coisa mais engraçada que você já fez bêbado(a)?",
        "Quem do grupo já bebeu algo que parecia suco de morango, mas não era?",
        "Qual foi a coisa mais estranha que você já pediu em um bar?",
        "Quem do grupo já bebeu algo que parecia suco de maçã, mas não era?",
        "Qual foi a coisa mais louca que você já fez por uma aposta envolvendo bebidas?",
        "Quem do grupo já bebeu algo que tinha gosto de suco de limão, mas não era?",
        "Qual foi a coisa mais engraçada que você já fez bêbado(a)?",
        "Quem do grupo já bebeu algo que parecia suco de manga, mas não era?",
        "Qual foi a coisa mais estranha que você já pediu em um bar?",
        "Quem do grupo já bebeu algo que parecia suco de goiaba, mas não era?",
        "Qual foi a coisa mais louca que você já fez por uma aposta envolvendo bebidas?",
        "Quem do grupo já bebeu algo que tinha gosto de suco de pêssego, mas não era?",
        "Qual foi a coisa mais engraçada que você já fez bêbado(a)?",
        "Quem do grupo já bebeu algo que parecia suco de amora, mas não era?",
        "Qual foi a coisa mais estranha que você já pediu em um bar?",
        "Quem do grupo já bebeu algo que parecia suco de framboesa, mas não era?",
        "Qual foi a coisa mais louca que você já fez por uma aposta envolvendo bebidas?",
        "Quem do grupo já bebeu algo que tinha gosto de suco de cereja, mas não era?",
        "Qual foi a coisa mais engraçada que você já fez bêbado(a)?",
        "Quem do grupo já bebeu algo que parecia suco de kiwi, mas não era?",
        "Qual foi a coisa mais estranha que você já pediu em um bar?",
        "Quem do grupo já bebeu algo que parecia suco de melancia, mas não era?",
        "Qual foi a coisa mais louca que você já fez por uma aposta envolvendo bebidas?",
        "Quem do grupo já bebeu algo que tinha gosto de suco de coco, mas não era?",
        "Qual foi a coisa mais engraçada que você já fez bêbado(a)?",
        "Quem do grupo já bebeu algo que parecia suco de açaí, mas não era?",
        "Qual foi a coisa mais estranha que você já pediu em um bar?",
        "Quem do grupo já bebeu algo que parecia suco de graviola, mas não era?",
        "Qual foi a coisa mais louca que você já fez por uma aposta envolvendo bebidas?",
        "Quem do grupo já bebeu algo que tinha gosto de suco de tangerina, mas não era?",
        "Qual foi a coisa mais engraçada que você já fez bêbado(a)?",
        "Quem do grupo já bebeu algo que parecia suco de acerola, mas não era?",
        "Qual foi a coisa mais estranha que você já pediu em um bar?",
        "Quem do grupo já bebeu algo que parecia suco de caju, mas não era?",
        "Qual foi a coisa mais louca que você já fez por uma aposta envolvendo bebidas?",
        "Quem do grupo já bebeu algo que tinha gosto de suco de pitanga, mas não era?",
        "Qual foi a coisa mais engraçada que você já fez bêbado(a)?",
        "Quem do grupo já bebeu algo que parecia suco de umbu, mas não era?",
        "Qual foi a coisa mais estranha que você já pediu em um bar?",
        "Quem do grupo já bebeu algo que parecia suco de jabuticaba, mas não era?",
        "Qual foi a coisa mais louca que você já fez por uma aposta envolvendo bebidas?",
        "Quem do grupo já bebeu algo que tinha gosto de suco de romã, mas não era?",
        "Qual foi a coisa mais engraçada que você já fez bêbado(a)?",
        "Quem do grupo já bebeu algo que parecia suco de figo, mas não era?",
        "Qual foi a coisa mais estranha que você já pediu em um bar?",
        "Quem do grupo já bebeu algo que parecia suco de pera, mas não era?",
        "Qual foi a coisa mais louca que você já fez por uma aposta envolvendo bebidas?"
    ]
  };
  
// Função para tocar sons
function playSound(soundFile) {
  const audio = new Audio(soundFile);
  audio.play().catch(error => {
    console.error("Erro ao reproduzir o som:", error);
  });
}

// Função para gerar uma pergunta aleatória
function getRandomQuestion(theme) {
  const questions = themes[theme];
  const randomIndex = Math.floor(Math.random() * questions.length);
  return questions[randomIndex];
}

// Seleciona elementos do DOM
const themeSelectionScreen = document.getElementById('theme-selection-screen');
const gameScreen = document.getElementById('game-screen');
const themeTitle = document.getElementById('theme-title');
const card = document.getElementById('card');
const questionElement = document.getElementById('question');
const backButton = document.getElementById('back-button');

// Evento para escolher o tema
document.querySelectorAll('.theme-button').forEach(button => {
  button.addEventListener('click', () => {
    playSound('sounds/button-click.mp3'); // Som ao clicar no botão
    const selectedTheme = button.getAttribute('data-theme');
    themeTitle.textContent = `Tema: ${button.textContent}`;
    themeSelectionScreen.classList.add('hidden');
    gameScreen.classList.remove('hidden');
    startGame(selectedTheme);

    // Altera a cor de fundo com base no tema
    document.body.className = selectedTheme;
  });
});

// Função para iniciar o jogo
function startGame(theme) {
  card.addEventListener('click', () => {
    playSound('sounds/card-flip.mp3'); // Som ao gerar pergunta
    const randomQuestion = getRandomQuestion(theme);
    questionElement.textContent = randomQuestion;
  });
}

// Botão de voltar ao menu
backButton.addEventListener('click', () => {
  playSound('sounds/button-click.mp3'); // Som ao clicar no botão
  gameScreen.classList.add('hidden');
  themeSelectionScreen.classList.remove('hidden');
  questionElement.textContent = "?"; // Reseta a pergunta
  document.body.className = ''; // Remove a cor de fundo
});